# Copyright (c) 2016-2021 Knuth Project developers.
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

# ------------------------------------------------------------------------------------------------------

build: false

environment:
    # VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"

    matrix:
      - WINDOWS_SDK_VERSION: "v7.1"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        nodejs_version: "5"

      - WINDOWS_SDK_VERSION: "v7.1"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        nodejs_version: "8"

      - WINDOWS_SDK_VERSION: "v7.1"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        nodejs_version: "7"

      - WINDOWS_SDK_VERSION: "v7.1"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        nodejs_version: "6"

      - WINDOWS_SDK_VERSION: "v7.1"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        nodejs_version: "4"
  


install:

  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  # - npm install
  - npm --version
  - npm -g install npm@next
  - npm --version
  - npm install -g node-gyp
  - npm install -g node-pre-gyp
  - npm install -g aws-sdk
  - npm install -g node-pre-gyp-github
  

  # - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  # - SET VS90COMNTOOLS=%VS140COMNTOOLS%
  # - cd "c:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\"
  # - ren "Visual C++ for Python" "Visual C++ for Python Do Not Use"
  # - cd "C:\Program Files (x86)\"
  # - ren "Microsoft Visual Studio 9.0" "Microsoft Visual Studio 9.0 Do Not Use"
  # - cp "c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdint.h" "C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\stdint.h"


  - pip --version
  # - pip install conan --upgrade
  - pip install kthbuild --upgrade
  - python --version
  - conan user # It creates the conan data directory


before_build:
  # - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" amd64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  # - IF "%PYTHON_ARCH%"=="64" (
  #     call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  #   ) ELSE (
  #     call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  #   )


# test_script:
build_script:
  - node --version
  - npm --version
  - python --version
  # - cl /version
  
  - echo "FerFerFer"
  - node -p "process.arch"
  - echo "FerFerFer"

  - conan user
  - conan remote add kth_temp https://api.bintray.com/conan/k-nuth/kth
  # - conan install .

  - npm install
  - node-pre-gyp configure build package
  # - node-pre-gyp configure --verbose
  # - node-pre-gyp build --verbose
  # - node-pre-gyp package --verbose
  - node-pre-gyp-github publish --release  || true
  
    # - cd %APPVEYOR_BUILD_FOLDER% 
    # - conan install .
    # # - pip install  -e .
    # - "%PYTHON%\\python.exe setup.py build"
    # - "%PYTHON%\\python.exe setup.py sdist"
    # - "%PYTHON%\\python.exe setup.py bdist_wheel"

    # - IF "%APPVEYOR_REPO_BRANCH%"=="master" (
    #     twine upload -u %PYPI_USER_NAME% -p %PYPI_PASSWORD% dist/* || true
    #   ) ELSE (
    #     twine upload -u %PYPI_USER_NAME% -p %PYPI_PASSWORD% --repository-url https://test.pypi.org/legacy/ dist/*  || true
    #   )


