# Copyright (c) 2016-2021 Knuth Project developers.
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

name: Build and Test

on: [push, pull_request]

jobs:
  generate-matrix:
    name: Generate Job Matrix
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate Job Matrix
        id: set-matrix
        env:
          MATRIX: '{"config": [{"name": "Linux NodeJS 14","nodejs_version": "14","os": "ubuntu-20.04","os_kind": "linux"},
                               {"name": "Linux NodeJS 12","nodejs_version": "12","os": "ubuntu-20.04","os_kind": "linux"},
                               {"name": "macOS NodeJS 14","nodejs_version": "14","os": "macos-10.15","os_kind": "macos"},
                               {"name": "macOS NodeJS 12","nodejs_version": "12","os": "macos-10.15","os_kind": "macos"},
                               {"name": "Windows NodeJS 14","nodejs_version": "14","os": "windows-2019","os_kind": "windows"},
                               {"name": "Windows NodeJS 12","nodejs_version": "12","os": "windows-2019","os_kind": "windows"},
                               ]}'
        run: |
          echo "${MATRIX}"
          echo "::set-output name=matrix::${MATRIX}"
          
  builds:
    needs: generate-matrix
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    name: ${{ matrix.config.name }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
  
      - name: Settting EnvVars (Unix)
        if: ${{ matrix.config.os_kind != 'windows' }}
        shell: bash
        run: |
          echo "NODEJS_VERSION=${{ matrix.config.nodejs_version }}" >> $GITHUB_ENV

      - name: Settting EnvVars (Windows)
        if: ${{ matrix.config.os_kind == 'windows' }}
        shell: powershell
        run: |
          echo "NODEJS_VERSION=${{ matrix.config.nodejs_version }}" >> $Env:GITHUB_ENV

      - name: Build (Linux)
        if: ${{ matrix.config.os_kind == 'linux' }}
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        shell: bash
        run: |
          # echo ${NPM_AUTH_TOKEN}
          # echo ${NPM_EMAIL}
          # echo ${NODEJS_VERSION}
          # echo ${NODE_PRE_GYP_GITHUB_TOKEN}
                  
          chmod a+x .travis/entrypoint.sh
          /usr/bin/docker run -u root --rm -e NPM_AUTH_TOKEN=$NPM_AUTH_TOKEN -e NPM_EMAIL=$NPM_EMAIL -e NODEJS_VERSION=$NODEJS_VERSION -e NODE_PRE_GYP_GITHUB_TOKEN=$NODE_PRE_GYP_GITHUB_TOKEN -v ${PWD}:/home/conan/project -v ${PWD}/.travis/entrypoint.sh:/tmp/entrypoint.sh conanio/gcc10 /bin/bash -c /tmp/entrypoint.sh

      - uses: actions/setup-node@v2
        if: ${{ matrix.config.os_kind != 'linux' }}
        with:
          node-version: '${{ matrix.config.nodejs_version }}'

      - name: Install (macOS)
        if: ${{ matrix.config.os_kind == 'macos' }}
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        shell: bash
        run: |
          set -x

          node --version
          npm --version

          brew update
          brew outdated pyenv || brew upgrade pyenv
          brew install pyenv-virtualenv
          # brew install cmake || true

          if which pyenv > /dev/null; then
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)" 
          fi

          pyenv install --list
          pyenv install 3.8.7
          pyenv virtualenv 3.8.7 conan

          pyenv rehash
          pyenv activate conan

          npm install -g node-gyp
          npm install -g @mapbox/node-pre-gyp
          # npm install -g aws-sdk
          npm install -g node-pre-gyp-github

          # pip install conan_package_tools --upgrade
          # pip install conan --upgrade
          pip install kthbuild --upgrade
          
          conan user

      - name: Build (macOS)
        if: ${{ matrix.config.os_kind == 'macos' }}
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        shell: bash
        run: |
          if which pyenv > /dev/null; then
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
          fi
          pyenv activate conan

          python --version
          conan user
          conan remote add kth_temp https://api.bintray.com/conan/k-nuth/kth || true
          conan install .

          npm install
          npm run test
          node-pre-gyp configure build package --verbose
          node-pre-gyp-github publish --release  || true

          # node-pre-gyp clean
          # node-gyp clean
          # npm install
          # npm publish || true

      - name: Install (Windows)
        if: ${{ matrix.config.os_kind == 'windows' }}
        shell: powershell
        run: |
          # Write-Host "CONAN_VISUAL_VERSIONS: $Env:CONAN_VISUAL_VERSIONS"

          $ErrorActionPreference = 'SilentlyContinue'

          npm --version
          npm -g install npm@next
          npm --version
          npm install -g node-gyp
          npm install -g @mapbox/node-pre-gyp
          npm install -g aws-sdk
          npm install -g node-pre-gyp-github

          pip --version
          pip install kthbuild --upgrade
          python --version
          conan user # It creates the conan data directory

          node --version
          npm --version
          python --version
          # cl /version

          Write-Host "----------------------------"
          node -p "process.arch"
          Write-Host "----------------------------"

          conan user
          conan remote add kth_temp https://api.bintray.com/conan/k-nuth/kth
          # conan install . -s compiler.runtime=MT
          conan user
          $ErrorActionPreference = 'Continue'


      - name: Build (Windows)
        if: ${{ matrix.config.os_kind == 'windows' }}
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        shell: powershell
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          
          npm install
          npm run test
          
          Remove-Item './deps' -Recurse

          node-pre-gyp configure build package
          # node-pre-gyp configure --verbose
          # node-pre-gyp build --verbose
          # node-pre-gyp package --verbose
          
          $ErrorActionPreference = 'SilentlyContinue'
          node-pre-gyp-github publish --release
          $ErrorActionPreference = 'Continue'

          # $ErrorActionPreference = 'SilentlyContinue'
          # conan remove "*" -f
          # conan remote remove kth
          # conan remote remove kthbuild_kth_temp_
          # $ErrorActionPreference = 'Continue'

# References:
  # https://github.com/radareorg/radare2